version: "3"

services:
  kafka0:
    container_name: kafka0
    image: apache/kafka:4.1.0
    ports:
      - ${KAFKA_PORT}:19092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL_SAME_HOST://:19092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka0:9092,EXTERNAL_SAME_HOST://localhost:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: ghcr.io/kafbat/kafka-ui:bcb9d18
    ports:
      - ${KAFKA_UI_PORT}:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      - kafka0

  producer:
    container_name: producer
    build:
      context: ./producer
      dockerfile: ./Dockerfile
    ports:
      - ${PRODUCER_PORT}:8080
    environment:
      CONFIG_PATH: ./config/config.yaml
    depends_on:
      - kafka0

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5

  consumer:
    container_name: consumer
    build:
      context: ./consumer
      dockerfile: ./Dockerfile
    ports:
      - ${CONSUMER_PORT}:8080
    environment:
      CONFIG_PATH: ./config/config.yaml
    depends_on:
      db:
        condition: service_healthy
      kafka0:
        condition: service_started
