env: debug

http_server:
  port: 8080
  Address: localhost
  timeout: 5s
  idle_timeout: 60s

kafka:
  bootstrap_servers: localhost:9090
  message_topic: messages
  flush_timeout: 500 #ms
  delivery_timeout: 500ms
  acks: 1
